name: ElectricSpawners
version: ${project.version}
author: TheBusyBiscuit
depend: [Slimefun]

api-version: 1.13

main: io.github.thebusybiscuit.electricspawners.ElectricSpawners

commands:
  electricspawners:
    usage: /electricspawners <reload>

permissions:
  electricspawners.reload:
    default: op